<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>SimLynx</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac"
                          Version="9.1.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection"
                          Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"
                          Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Logging"
                          Version="10.0.5" />
        <PackageReference Include="Semver"
                          Version="3.0.0" />
    </ItemGroup>
</Project>
