<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>SimLynx</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.3.2" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
        <PackageReference Include="Semver" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    </ItemGroup>
</Project>
